### ISSUE TITLE
Exception on HEAD access in the UI

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Fenrir#45]
1. Start `fenrir ui` in its own repository
2. Select branch `refs/remotes/origin/HEAD`
3. It will fail with an exception:

```
Exception: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Fenrir.Commands.parseCommitBody(String path, String hash) in W:\Projects\Fenrir\Fenrir\Commands.fs:line 92
   at <StartupCode$Fenrir>.$GitRepositoryModel.ReadCommitsAsync@15-1.GenerateNext(IEnumerable`1& next) in W:\Projects\Fenrir\Fenrir\Ui\GitRepositoryModel.fs:line 17
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 403
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 825
   at <StartupCode$Fenrir>.$GitRepositoryModel.ReadCommitsAsync@14.Invoke(Unit unitVar) in W:\Projects\Fenrir\Fenrir\Ui\GitRepositoryModel.fs:line 14
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at <StartupCode$Fenrir>.$CommitsViewModel.Initialize@43-18.Invoke(AsyncActivation`1 ctxt) in W:\Projects\Fenrir\Fenrir\Ui\CommitsViewModel.fs:line 43
   at Fenrir.Ui.Framework.Async.runTask@8-4.Invoke(AsyncActivation`1 ctxt) in W:\Projects\Fenrir\Fenrir.Ui.Framework\Async.fs:line 8
   at Fenrir.Ui.Framework.Async.runTask@7-7.Invoke(AsyncActivation`1 ctxt) in W:\Projects\Fenrir\Fenrir.Ui.Framework\Async.fs:line 7
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
Process terminated. Unhandled async exception
   at System.Environment.FailFast(System.String, System.Exception)
   at Fenrir.Ui.Framework.Async+runTask@7-5.Invoke(System.Exception)
   at Fenrir.Ui.Framework.Async+runTask@7-6.Invoke(System.Exception)
   at Fenrir.Ui.Framework.Async+runTask@7-8.Invoke(System.Exception)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Control.AsyncActivation`1<System.__Canon>, Microsoft.FSharp.Core.FSharpFunc`2<System.Exception,Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Control.FSharpAsync`1<System.__Canon>>>, System.Runtime.ExceptionServices.ExceptionDispatchInfo)
   at Microsoft.FSharp.Control.Trampoline.Execute(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.AsyncReturn>)
   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.AsyncReturn>)
   at <StartupCode$FSharp-Core>.$Async+-ctor@163-1.Invoke(System.Object)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Fenrir.Commands.parseCommitBody(String path, String hash) in W:\Projects\Fenrir\Fenrir\Commands.fs:line 92
   at <StartupCode$Fenrir>.$GitRepositoryModel.ReadCommitsAsync@15-1.GenerateNext(IEnumerable`1& next) in W:\Projects\Fenrir\Fenrir\Ui\GitRepositoryModel.fs:line 17
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 403
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 825
   at <StartupCode$Fenrir>.$GitRepositoryModel.ReadCommitsAsync@14.Invoke(Unit unitVar) in W:\Projects\Fenrir\Fenrir\Ui\GitRepositoryModel.fs:line 14
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at <StartupCode$Fenrir>.$CommitsViewModel.Initialize@43-18.Invoke(AsyncActivation`1 ctxt) in W:\Projects\Fenrir\Fenrir\Ui\CommitsViewModel.fs:line 43
   at Fenrir.Ui.Framework.Async.runTask@8-4.Invoke(AsyncActivation`1 ctxt) in W:\Projects\Fenrir\Fenrir.Ui.Framework\Async.fs:line 8
   at Fenrir.Ui.Framework.Async.runTask@7-7.Invoke(AsyncActivation`1 ctxt) in W:\Projects\Fenrir\Fenrir.Ui.Framework\Async.fs:line 7
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
```

**Comment by rstm-sf** [comment]
It looks like #39

**Comment by ForNeVeR** [comment]
Well, to, me, it doesn't. In #39, there's valid content and no exceptions. And here it's an exception.
