### ISSUE TITLE
Unable to load shared library 'libncursesw.so.5' or one of its dependencies

### ISSUE THREAD

**Issue by rstm-sf** [ForNeVeR/Fenrir#48]
Hello!

```sh
$ dotnet run --project Fenrir ui
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libncursesw.so.5' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibncursesw.so.5: cannot open shared object file: No such file or directory
   at ConsoleFramework.Native.NCurses.initscr()
   at ConsoleFramework.ConsoleApplication.runLinux(Control control)
   at ConsoleFramework.ConsoleApplication.Run(Control control)
   at Fenrir.Ui.EntryPoint.run(String path) in /Fenrir/Fenrir/Ui/EntryPoint.fs:line 55
   at Fenrir.Program.main(String[] argv) in /Fenrir/Fenrir/Program.fs:line 167
```

```sh
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```sh
$ locate libncursesw
/usr/lib/x86_64-linux-gnu/libncursesw.so.6
/usr/lib/x86_64-linux-gnu/libncursesw.so.6.2
/usr/share/doc/libncursesw6
/var/lib/dpkg/info/libncursesw6:amd64.list
/var/lib/dpkg/info/libncursesw6:amd64.md5sums
/var/lib/dpkg/info/libncursesw6:amd64.shlibs
/var/lib/dpkg/info/libncursesw6:amd64.symbols
/var/lib/dpkg/info/libncursesw6:amd64.triggers
```

---
It's work after
```sh
$ sudo apt install libncursesw5
$ sudo apt install libtermkey-dev
```

**Comment by rstm-sf** [comment]
For libtermkey in the ConsoleFramework it is [indicated](https://github.com/elw00d/consoleframework#running-examples) that the user needs to add a dependency

libncursesw5 starts to be deprecated

**Comment by ForNeVeR** [comment]
Well, could you raise an issue in the ConsoleFramework about `libncursesw5` being deprecated?

**Comment by rstm-sf** [comment]
It seems to me that it is needed to support 18.04 and is present for 20.04 as legacy support, judging by [this](https://pkgs.org/download/libncursesw5) resource. I guess we can raise for the future
